In [15]:
import KID_model_functions as kids
import fitting_KID_model_functions as fitkids
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from astropy import units as u

In [16]:
alpha = 0.73*u.dimensionless_unscaled
f = 331.6*u.MHz
Tstage = 0.215*u.K
Tc = 1.39*u.K
TBB_0 = 6.0*u.K
V = 38*1.5*0.8*np.power(u.micron,3) # volume w/20nm film is 38um3, multiply by 1.5 for ~30nm film, minus 20% for overetching trace width
eta_pb = 0.57
nu_opt = (350*u.micron).to(u.GHz,equivalencies=u.spectral())
N0=1.72e10*np.power(u.micron,-3)*np.power(u.eV,-1)

In [17]:
trans=0.03

eta_opt = 0.8*u.dimensionless_unscaled
n_star = 1318*(np.power(u.micron,-3))
tau_max = 35*u.microsecond

In [18]:
TBBoptdata,f0optdata,xoptdata,sxxoptdata = np.loadtxt('optical_response_evap_devices/CD012_reduced_Res0.csv',delimiter=',',unpack=True)

In [19]:
Pincoptdata = kids.TBB_to_Pinc(TBBoptdata,trans=trans)

In [20]:
TBBoptpts = np.sort(list(set(TBBoptdata)))
Pincoptpts = kids.TBB_to_Pinc(TBBoptpts,trans=trans)

In [21]:
f0optpts = []
f0opterr = []
xoptpts = []
xopterr = []
sxxoptpts = []
sxxopterr = []


In [22]:
for temp in TBBoptpts:
    inds = np.where(TBBoptdata == temp)
    
    f0optpts.append(np.average(f0optdata[inds]))
    f0opterr.append(np.std(f0optdata[inds])/np.sqrt(len(inds)))
    
    xoptpts.append(np.average(xoptdata[inds]))
    xopterr.append(np.std(xoptdata[inds])/np.sqrt(len(inds)))
    
    sxxoptpts.append(np.average(sxxoptdata[inds]))
    sxxopterr.append(np.std(sxxoptdata[inds])/np.sqrt(len(inds)))
    

In [23]:
Tstagedarkdata,f0darkdata,xdarkdata,sxxdarkdata = np.loadtxt('optical_response_evap_devices/CD011_reduced_Res0.csv',delimiter=',',unpack=True)

In [24]:
Tstagedarkpts = np.sort(list(set(Tstagedarkdata)))
f0darkpts = []
f0darkerr = []
xdarkpts = []
xdarkerr = []
sxxdarkpts = []
sxxdarkerr = []

In [25]:
for temp in Tstagedarkpts:
    inds = np.where(Tstagedarkdata == temp)
    
    f0darkpts.append(np.average(f0darkdata[inds]))
    f0darkerr.append(np.std(f0darkdata[inds])/np.sqrt(len(inds)))
    
    xdarkpts.append(np.average(xdarkdata[inds]))
    xdarkerr.append(np.std(xdarkdata[inds])/np.sqrt(len(inds)))
    
    sxxdarkpts.append(np.average(sxxdarkdata[inds]))
    sxxdarkerr.append(np.std(sxxdarkdata[inds])/np.sqrt(len(inds)))
    

In [31]:
# triple simultaneous fit of x_opt,sxx_opt,sxx_dark for n_star,tau_max,eta_Opt, df,Sxx_0_Opt,S_xx_0_dark
data0 = np.array([TBBoptpts,TBBoptpts,Tstagedarkpts])

np.array(Tstagedarkpts)

array([0.215, 0.225, 0.25 , 0.275, 0.3  , 0.325])

In [30]:
Tstage0 = .215*u.K
data = np.array([data0,alpha,f,Tstage0,Tc,V,eta_pb,nu_opt,trans,N0])
ydata = np.array([xoptpts,sxxoptpts,sxxdarkpts])
yerr = np.array([xopterr,sxxopterr,sxxdarkerr])
# parameters: n_star,tau_max,eta_opt,df,Sxx_0_opt,Sxx_0_dark
# p0 = [1000*(np.power(u.micron,-3)),50*u.microsecond,.8,1e-8,1e-17,1e-17]
p0 = [1000,50,.8,1e-8,1e-17,1e-17]
bounds = ([10,10,0,0,1e-19,1e-19],[1e5,1e4,1,1e-17,1e-17])

d2 = data.flatten()
d2

array([array([array([5.61, 5.75, 5.95, 6.65, 7.1 , 7.45, 7.8 ]),
       array([5.61, 5.75, 5.95, 6.65, 7.1 , 7.45, 7.8 ]),
       array([0.215, 0.225, 0.25 , 0.275, 0.3  , 0.325])], dtype=object),
       <Quantity 0.73>, <Quantity 331.6 MHz>, <Quantity 0.215 K>,
       <Quantity 1.39 K>, <Quantity 45.6 micron3>, 0.57,
       <Quantity 856.54988 GHz>, 0.03,
       <Quantity 1.72e+10 1 / (eV micron3)>], dtype=object)

In [27]:
comb_popt,comb_pcov = curve_fit(fitkids.x_Sxx_dark_opt_simulfit,data,ydata,p0=p0)

TBBxOpt shape: (7,)
TBBSxxOpt shape: (7,)
Tstagedark shape: (6,)
glom shape: (3,)


TypeError: Improper input: N=6 must not exceed M=3

In [ ]:
np.shape(ydata)

In [ ]:
alpha = 0.73*u.dimensionless_unscaled
f = 331.6*u.MHz
Tc = 1.39*u.K
TBB_0 = 6.0*u.K
V = 76*np.power(u.micron,3)#38*1.5*0.8*np.power(u.micron,3) # volume w/20nm film is 38um3, multiply by 1.5 for ~30nm film, minus 20% for overetching trace width
eta_pb = 0.57
nu_opt = (350*u.micron).to(u.GHz,equivalencies=u.spectral())
N0=1.72e10*np.power(u.micron,-3)*np.power(u.eV,-1)

trans=0

eta_opt = 0.17*u.dimensionless_unscaled
n_star = 1392*(np.power(u.micron,-3))
tau_max = 20*u.microsecond

Sxx_0dark = 1.75e-17*np.power(u.Hz,-1)

Tstagedarkmod = np.linspace(0.210,0.35,num=50)
Sxxdarkmod = kids.Sxx(alpha,f,Tstagedarkmod,Tc,TBB_0,V,n_star,tau_max,eta_pb,nu_opt,eta_opt,trans=0,N0=N0)+Sxx_0dark

In [ ]:
alpha = 0.73*u.dimensionless_unscaled
f = 331.6*u.MHz
Tc = 1.39*u.K
TBB_0 = 6.0*u.K
V = 38*1.5*0.8*np.power(u.micron,3) # volume w/20nm film is 38um3, multiply by 1.5 for ~30nm film, minus 20% for overetching trace width
eta_pb = 0.57
nu_opt = (350*u.micron).to(u.GHz,equivalencies=u.spectral())
N0=1.72e10*np.power(u.micron,-3)*np.power(u.eV,-1)

trans=0

eta_opt = 0.8*u.dimensionless_unscaled
n_star = 100*(np.power(u.micron,-3))
tau_max = 100*u.microsecond

Sxx_0dark = .5e-17*np.power(u.Hz,-1)

Tstagedarkmod2 = np.linspace(0.210,0.35,num=50)
Sxxdarkmod2 = kids.Sxx(alpha,f,Tstagedarkmod,Tc,TBB_0,V,n_star,tau_max,eta_pb,nu_opt,eta_opt,trans=0,N0=N0)+Sxx_0dark

In [ ]:
plt.errorbar(x=Tstagedarkpts,y=sxxdarkpts,yerr=sxxdarkerr,linestyle=None,fmt='s',markerfacecolor='w',markeredgecolor='k',ecolor='k',label='data')
plt.plot(Tstagedarkmod,Sxxdarkmod,'g-',label='Sputtered device Model')
plt.plot(Tstagedarkmod2,Sxxdarkmod2,'b:',label='Model 2')
plt.ticklabel_format(axis='y',style='sci',scilimits=(0,0))
plt.xlabel(r'$T_{stage}$ (K)')
plt.ylabel(r'$S_{xx}$ (Hz$^{-1}$)')
plt.title(r'Dark test (CD011), f0$\approx$331.6 MHz')
plt.legend(loc='upper left')
plt.savefig('CD011_res0_sxx_vs_Tstage.png')
#plt.plot(Tstagedarkdata,sxxdarkdata,'ko')

In [ ]:
alpha = 0.73*u.dimensionless_unscaled
f = 331.6*u.MHz
Tc = 1.39*u.K
Tstage_0 = .215*u.K
V = 76*np.power(u.micron,3)#38*1.5*0.8*np.power(u.micron,3) # volume w/20nm film is 38um3, multiply by 1.5 for ~30nm film, minus 20% for overetching trace width
eta_pb = 0.57
nu_opt = (350*u.micron).to(u.GHz,equivalencies=u.spectral())
N0=1.72e10*np.power(u.micron,-3)*np.power(u.eV,-1)

trans=0.03

eta_opt = 0.17*u.dimensionless_unscaled
n_star = 1392*(np.power(u.micron,-3))
tau_max = 20*u.microsecond

Sxx_0opt = 1.75e-17*np.power(u.Hz,-1)

TBBoptmod = np.linspace(5,8,num=50)
Pincoptmod = kids.TBB_to_Pinc(TBBoptmod,trans)
xoptmod = kids.xMB(alpha,f,Tstage_0,Tc,TBBoptmod,V,n_star,tau_max,eta_pb,eta_opt,trans=trans,N0=N0)
Sxxoptmod = kids.Sxx(alpha,f,Tstage_0,Tc,TBBoptmod,V,n_star,tau_max,eta_pb,nu_opt,eta_opt,trans=trans,N0=N0)+Sxx_0dark

In [ ]:
alpha = 0.73*u.dimensionless_unscaled
f = 331.6*u.MHz
Tc = 1.39*u.K
Tstage_0 = .215*u.K
V = 38*1.5*0.8*np.power(u.micron,3) # volume w/20nm film is 38um3, multiply by 1.5 for ~30nm film, minus 20% for overetching trace width
eta_pb = 0.57
nu_opt = (350*u.micron).to(u.GHz,equivalencies=u.spectral())
N0=1.72e10*np.power(u.micron,-3)*np.power(u.eV,-1)

trans=0.03

eta_opt = 0.8*u.dimensionless_unscaled
n_star = 100*(np.power(u.micron,-3))
tau_max = 50*u.microsecond

Sxx_0opt = 1.75e-17*np.power(u.Hz,-1)

TBBoptmod2 = np.linspace(5,8,num=50)
Pincoptmod2 = kids.TBB_to_Pinc(TBBoptmod2,trans)
xoptmod2 = kids.xMB(alpha,f,Tstage_0,Tc,TBBoptmod,V,n_star,tau_max,eta_pb,eta_opt,trans=trans,N0=N0)
Sxxoptmod2 = kids.Sxx(alpha,f,Tstage_0,Tc,TBBoptmod,V,n_star,tau_max,eta_pb,nu_opt,eta_opt,trans=trans,N0=N0)+Sxx_0dark

In [ ]:
plt.errorbar(x=Pincoptpts.value,y=xoptpts,yerr=xopterr,linestyle=None,fmt='s',markerfacecolor='w',markeredgecolor='k',ecolor='k',label='data')
#plt.plot(Pincoptmod,xoptmod,'g-',label='Sputtered device model')
#plt.plot(Pincoptmod2,xoptmod2,'b:',label='Model 2')
plt.ticklabel_format(axis='y',style='sci',scilimits=(0,0))
plt.xlabel(r'$P_{inc}$ (pW)')
plt.ylabel('x = df/f')
plt.title(r'Optical test (CD012), f0$\approx$331.6 MHz' + '\n' + 'With 3% transmissive mask')
plt.legend(loc='lower left')
plt.savefig('CD012_res0_x_vs_Pinc.png')


In [ ]:
plt.errorbar(x=Pincoptpts.value,y=sxxoptpts,yerr=sxxopterr,linestyle=None,fmt='s',markerfacecolor='w',markeredgecolor='k',ecolor='k',label='data')
#plt.plot(Pincoptmod,Sxxoptmod,'g-',label='Sputtered device model')
#plt.plot(Pincoptmod2,Sxxoptmod2,'b:',label='Model 2')
plt.ticklabel_format(axis='y',style='sci',scilimits=(0,0))
plt.xlabel(r'$P_{inc}$ (pW)')
plt.ylabel(r'$S_{xx}$ (Hz$^{-1}$)')
plt.title(r'Optical test (CD012), f0$\approx$331.6 MHz' + '\n' + 'With 3% transmissive mask')
plt.legend(loc='lower right')
plt.savefig('CD012_res0_sxx_vs_Pinc.png')
#plt.plot(Pincoptdata,sxxoptdata,'ko')

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


data = [[ 66386, 174296,  75131, 577908,  32015],
        [ 58230, 381139,  78045,  99308, 160454],
        [ 89135,  80552, 152558, 497981, 603535],
        [ 78415,  81858, 150656, 193263,  69638],
        [139361, 331509, 343164, 781380,  52269]]

columns = ('Freeze', 'Wind', 'Flood', 'Quake', 'Hail')
rows = ['%d year' % x for x in (100, 50, 20, 10, 5)]

values = np.arange(0, 2500, 500)
value_increment = 1000

# Get some pastel shades for the colors
colors = plt.cm.BuPu(np.linspace(0, 0.5, len(rows)))
n_rows = len(data)

index = np.arange(len(columns)) + 0.3
bar_width = 0.4

# Initialize the vertical-offset for the stacked bar chart.
y_offset = np.zeros(len(columns))

# Plot bars and create text labels for the table
cell_text = []
for row in range(n_rows):
    plt.bar(index, data[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + data[row]
    cell_text.append(['%1.1f' % (x / 1000.0) for x in y_offset])
# Reverse colors and text labels to display the last value at the top.
colors = colors[::-1]
cell_text.reverse()

# Add a table at the bottom of the axes
the_table = plt.table(cellText=cell_text,
                      rowLabels=rows,
                      rowColours=colors,
                      colLabels=columns,
                      loc='bottom')

# Adjust layout to make room for the table:
plt.subplots_adjust(left=0.2, bottom=0.2)

plt.ylabel("Loss in ${0}'s".format(value_increment))
plt.yticks(values * value_increment, ['%d' % val for val in values])
plt.xticks([])
plt.title('Loss by Disaster')

plt.show()

In [ ]:
cell_text

In [ ]:
rows

In [ ]:
columns